'use client';

import { useState } from 'react';
import { Calculator, Copy, Check } from 'lucide-react';

interface PositionCalculatorProps {
    symbol: string;
    entryPrice: number;
    stopLoss?: number;
    takeProfit?: number;
    action: 'LONG' | 'SHORT' | 'WAIT';
    reason: string;
    confidence: string;
    lang: 'en' | 'de';
    formatPrice: (price: number) => string;
}

export default function PositionCalculator({
    symbol, entryPrice, stopLoss, takeProfit, action, reason, confidence, lang, formatPrice
}: PositionCalculatorProps) {
    const [accountSize, setAccountSize] = useState<string>('10000');
    const [riskPercent, setRiskPercent] = useState<string>('1');
    const [copied, setCopied] = useState(false);

    const t = {
        title: lang === 'de' ? 'Positionsrechner' : 'Position Calculator',
        account: lang === 'de' ? 'Kontogröße' : 'Account Size',
        risk: lang === 'de' ? 'Risiko %' : 'Risk %',
        posSize: lang === 'de' ? 'Positionsgröße' : 'Position Size',
        shares: lang === 'de' ? 'Stück' : 'Shares',
        riskAmount: lang === 'de' ? 'Risiko-Betrag' : 'Risk Amount',
        copy: lang === 'de' ? 'Trade-Setup kopieren' : 'Copy Trade Setup',
        copied: lang === 'de' ? 'Kopiert!' : 'Copied!',
    };

    const account = parseFloat(accountSize) || 0;
    const riskPct = parseFloat(riskPercent) || 0;
    const riskAmount = account * (riskPct / 100);

    let positionSize = 0;
    let shares = 0;
    if (stopLoss && entryPrice) {
        const riskPerShare = Math.abs(entryPrice - stopLoss);
        if (riskPerShare > 0) {
            shares = Math.floor(riskAmount / riskPerShare);
            positionSize = shares * entryPrice;
        }
    }

    const copyTradeSetup = () => {
        const lines = [
            `--- Trade Setup: ${symbol} ---`,
            `Signal: ${action} (${confidence})`,
            `Entry: ${formatPrice(entryPrice)}`,
            stopLoss ? `Stop Loss: ${formatPrice(stopLoss)}` : '',
            takeProfit ? `Take Profit: ${formatPrice(takeProfit)}` : '',
            stopLoss && takeProfit ? `R:R: 1:${(Math.abs(takeProfit - entryPrice) / Math.abs(entryPrice - stopLoss)).toFixed(1)}` : '',
            `Reason: ${reason}`,
            shares > 0 ? `\nPosition: ${shares} shares ($${positionSize.toLocaleString()})` : '',
            shares > 0 ? `Risk: $${riskAmount.toFixed(0)} (${riskPct}% of $${account.toLocaleString()})` : '',
            `\nGenerated by Swing Bot Pro`,
        ].filter(Boolean).join('\n');

        navigator.clipboard.writeText(lines).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    if (action === 'WAIT' || !stopLoss) return null;

    return (
        <div className="bg-white dark:bg-gray-800 rounded-3xl p-5 md:p-8 shadow-sm border border-gray-100 dark:border-gray-700">
            <div className="flex items-center justify-between mb-5">
                <div className="flex items-center gap-2">
                    <div className="p-1.5 bg-amber-100 dark:bg-amber-900/30 rounded-lg text-amber-600">
                        <Calculator size={18} />
                    </div>
                    <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">{t.title}</h3>
                </div>
                <button
                    onClick={copyTradeSetup}
                    className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold rounded-lg border transition-all
                        bg-gray-50 dark:bg-gray-700 border-gray-200 dark:border-gray-600 text-gray-600 dark:text-gray-300
                        hover:bg-indigo-50 dark:hover:bg-indigo-900/30 hover:border-indigo-200 hover:text-indigo-600"
                >
                    {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
                    {copied ? t.copied : t.copy}
                </button>
            </div>

            <div className="grid grid-cols-2 gap-4 mb-5">
                <div>
                    <label className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 block">{t.account} ($)</label>
                    <input
                        type="number"
                        value={accountSize}
                        onChange={(e) => setAccountSize(e.target.value)}
                        className="w-full bg-gray-50 dark:bg-gray-700 rounded-xl px-3 py-2 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/50 dark:text-white"
                    />
                </div>
                <div>
                    <label className="text-xs font-bold text-gray-400 dark:text-gray-500 uppercase mb-1 block">{t.risk}</label>
                    <input
                        type="number"
                        value={riskPercent}
                        onChange={(e) => setRiskPercent(e.target.value)}
                        step="0.5"
                        min="0.1"
                        max="10"
                        className="w-full bg-gray-50 dark:bg-gray-700 rounded-xl px-3 py-2 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/50 dark:text-white"
                    />
                </div>
            </div>

            <div className="grid grid-cols-3 gap-3">
                <div className="p-3 bg-amber-50 dark:bg-amber-900/20 rounded-xl border border-amber-100 dark:border-amber-800/30">
                    <span className="text-xs font-bold text-amber-500 uppercase block mb-1">{t.riskAmount}</span>
                    <span className="text-lg font-bold text-amber-700 dark:text-amber-400">${riskAmount.toFixed(0)}</span>
                </div>
                <div className="p-3 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-100 dark:border-blue-800/30">
                    <span className="text-xs font-bold text-blue-500 uppercase block mb-1">{t.shares}</span>
                    <span className="text-lg font-bold text-blue-700 dark:text-blue-400">{shares}</span>
                </div>
                <div className="p-3 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl border border-indigo-100 dark:border-indigo-800/30">
                    <span className="text-xs font-bold text-indigo-500 uppercase block mb-1">{t.posSize}</span>
                    <span className="text-lg font-bold text-indigo-700 dark:text-indigo-400">${positionSize.toLocaleString()}</span>
                </div>
            </div>
        </div>
    );
}
