export interface Asset {
    symbol: string;
    name: string;
    category: 'Stock' | 'Crypto' | 'Index' | 'Forex';
}

export const ASSETS: Asset[] = [
    // --- Indices / ETFs ---
    { symbol: 'SPY', name: 'S&P 500', category: 'Index' },
    { symbol: 'VOO', name: 'Vanguard S&P 500', category: 'Index' },
    { symbol: 'QQQ', name: 'Nasdaq 100', category: 'Index' },
    { symbol: 'IWM', name: 'Russell 2000', category: 'Index' },
    { symbol: 'DIA', name: 'Dow Jones', category: 'Index' },
    { symbol: 'SMH', name: 'Semiconductors ETF', category: 'Index' },
    { symbol: 'SOXX', name: 'iShares Semiconductor', category: 'Index' },
    { symbol: 'ARKK', name: 'ARK Innovation', category: 'Index' },
    { symbol: 'XLK', name: 'Technology Select', category: 'Index' },
    { symbol: 'XLE', name: 'Energy Select', category: 'Index' },
    { symbol: 'XLF', name: 'Financial Select', category: 'Index' },
    { symbol: 'GLD', name: 'Gold', category: 'Index' },
    { symbol: 'SLV', name: 'Silver', category: 'Index' },
    { symbol: 'TLT', name: '20+ Yr Treasury', category: 'Index' },
    { symbol: 'VIX', name: 'Volatility Index', category: 'Index' },
    { symbol: 'EEM', name: 'Emerging Markets', category: 'Index' },
    { symbol: 'KWEB', name: 'China Internet ETF', category: 'Index' },

    // --- Crypto ---
    { symbol: 'BTC-USD', name: 'Bitcoin', category: 'Crypto' },
    { symbol: 'ETH-USD', name: 'Ethereum', category: 'Crypto' },
    { symbol: 'SOL-USD', name: 'Solana', category: 'Crypto' },
    { symbol: 'BNB-USD', name: 'BNB', category: 'Crypto' },
    { symbol: 'XRP-USD', name: 'XRP', category: 'Crypto' },
    { symbol: 'DOGE-USD', name: 'Dogecoin', category: 'Crypto' },
    { symbol: 'ADA-USD', name: 'Cardano', category: 'Crypto' },
    { symbol: 'AVAX-USD', name: 'Avalanche', category: 'Crypto' },
    { symbol: 'DOT-USD', name: 'Polkadot', category: 'Crypto' },
    { symbol: 'LINK-USD', name: 'Chainlink', category: 'Crypto' },
    { symbol: 'MATIC-USD', name: 'Polygon', category: 'Crypto' },
    { symbol: 'SHIB-USD', name: 'Shiba Inu', category: 'Crypto' },
    { symbol: 'LTC-USD', name: 'Litecoin', category: 'Crypto' },
    { symbol: 'UNI-USD', name: 'Uniswap', category: 'Crypto' },
    { symbol: 'BCH-USD', name: 'Bitcoin Cash', category: 'Crypto' },
    { symbol: 'NEAR-USD', name: 'NEAR Protocol', category: 'Crypto' },
    { symbol: 'SUI20947-USD', name: 'Sui', category: 'Crypto' },
    { symbol: 'TRX-USD', name: 'Tron', category: 'Crypto' },
    { symbol: 'TON11419-USD', name: 'Toncoin', category: 'Crypto' },
    { symbol: 'RENDER-USD', name: 'Render', category: 'Crypto' },
    { symbol: 'PEPE24478-USD', name: 'Pepe', category: 'Crypto' },
    { symbol: 'ARB11841-USD', name: 'Arbitrum', category: 'Crypto' },

    // --- Stocks: Big Tech / AI / Software ---
    { symbol: 'NVDA', name: 'NVIDIA', category: 'Stock' },
    { symbol: 'AAPL', name: 'Apple', category: 'Stock' },
    { symbol: 'MSFT', name: 'Microsoft', category: 'Stock' },
    { symbol: 'AMZN', name: 'Amazon', category: 'Stock' },
    { symbol: 'GOOGL', name: 'Alphabet', category: 'Stock' },
    { symbol: 'META', name: 'Meta', category: 'Stock' },
    { symbol: 'TSLA', name: 'Tesla', category: 'Stock' },
    { symbol: 'AMD', name: 'AMD', category: 'Stock' },
    { symbol: 'AVGO', name: 'Broadcom', category: 'Stock' },
    { symbol: 'TSM', name: 'Taiwan Semi', category: 'Stock' },
    { symbol: 'ASML', name: 'ASML', category: 'Stock' },
    { symbol: 'ORCL', name: 'Oracle', category: 'Stock' },
    { symbol: 'CRM', name: 'Salesforce', category: 'Stock' },
    { symbol: 'ADBE', name: 'Adobe', category: 'Stock' },
    { symbol: 'INTC', name: 'Intel', category: 'Stock' },
    { symbol: 'IBM', name: 'IBM', category: 'Stock' },
    { symbol: 'PLTR', name: 'Palantir', category: 'Stock' },
    { symbol: 'SMCI', name: 'Super Micro', category: 'Stock' },
    { symbol: 'NOW', name: 'ServiceNow', category: 'Stock' },
    { symbol: 'UBER', name: 'Uber', category: 'Stock' },
    { symbol: 'ABNB', name: 'Airbnb', category: 'Stock' },
    { symbol: 'CRWD', name: 'CrowdStrike', category: 'Stock' },
    { symbol: 'PANW', name: 'Palo Alto', category: 'Stock' },
    { symbol: 'SNOW', name: 'Snowflake', category: 'Stock' },
    { symbol: 'MSTR', name: 'MicroStrategy', category: 'Stock' },
    { symbol: 'ARM', name: 'ARM Holdings', category: 'Stock' },
    { symbol: 'MRVL', name: 'Marvell Technology', category: 'Stock' },
    { symbol: 'VRT', name: 'Vertiv', category: 'Stock' },
    { symbol: 'DELL', name: 'Dell Technologies', category: 'Stock' },
    { symbol: 'ANET', name: 'Arista Networks', category: 'Stock' },
    { symbol: 'APP', name: 'AppLovin', category: 'Stock' },
    { symbol: 'TTD', name: 'The Trade Desk', category: 'Stock' },
    { symbol: 'DDOG', name: 'Datadog', category: 'Stock' },
    { symbol: 'SHOP', name: 'Shopify', category: 'Stock' },
    { symbol: 'NET', name: 'Cloudflare', category: 'Stock' },
    { symbol: 'ZS', name: 'Zscaler', category: 'Stock' },
    { symbol: 'FTNT', name: 'Fortinet', category: 'Stock' },
    { symbol: 'MDB', name: 'MongoDB', category: 'Stock' },
    { symbol: 'AMAT', name: 'Applied Materials', category: 'Stock' },
    { symbol: 'LRCX', name: 'Lam Research', category: 'Stock' },
    { symbol: 'KLAC', name: 'KLA Corp', category: 'Stock' },
    { symbol: 'MU', name: 'Micron Technology', category: 'Stock' },
    { symbol: 'QCOM', name: 'Qualcomm', category: 'Stock' },

    // --- Stocks: Strong Momentum / Compounders ---
    { symbol: 'AXON', name: 'Axon Enterprise', category: 'Stock' },
    { symbol: 'FICO', name: 'Fair Isaac', category: 'Stock' },
    { symbol: 'CEG', name: 'Constellation Energy', category: 'Stock' },
    { symbol: 'VST', name: 'Vistra Energy', category: 'Stock' },
    { symbol: 'SPOT', name: 'Spotify', category: 'Stock' },
    { symbol: 'MNST', name: 'Monster Beverage', category: 'Stock' },

    // --- Stocks: Finance / Fintech ---
    { symbol: 'JPM', name: 'JPMorgan', category: 'Stock' },
    { symbol: 'BAC', name: 'Bank of America', category: 'Stock' },
    { symbol: 'V', name: 'Visa', category: 'Stock' },
    { symbol: 'MA', name: 'Mastercard', category: 'Stock' },
    { symbol: 'GS', name: 'Goldman Sachs', category: 'Stock' },
    { symbol: 'MS', name: 'Morgan Stanley', category: 'Stock' },
    { symbol: 'BLK', name: 'BlackRock', category: 'Stock' },
    { symbol: 'COIN', name: 'Coinbase', category: 'Stock' },
    { symbol: 'HOOD', name: 'Robinhood', category: 'Stock' },
    { symbol: 'PYPL', name: 'PayPal', category: 'Stock' },
    { symbol: 'SQ', name: 'Block', category: 'Stock' },
    { symbol: 'MARA', name: 'Marathon Digital', category: 'Stock' },
    { symbol: 'RIOT', name: 'Riot Platforms', category: 'Stock' },

    // --- Stocks: Consumer & Retail ---
    { symbol: 'WMT', name: 'Walmart', category: 'Stock' },
    { symbol: 'COST', name: 'Costco', category: 'Stock' },
    { symbol: 'TGT', name: 'Target', category: 'Stock' },
    { symbol: 'KO', name: 'Coca-Cola', category: 'Stock' },
    { symbol: 'PEP', name: 'PepsiCo', category: 'Stock' },
    { symbol: 'MCD', name: 'McDonald\'s', category: 'Stock' },
    { symbol: 'SBUX', name: 'Starbucks', category: 'Stock' },
    { symbol: 'NKE', name: 'Nike', category: 'Stock' },
    { symbol: 'DIS', name: 'Disney', category: 'Stock' },
    { symbol: 'NFLX', name: 'Netflix', category: 'Stock' },
    { symbol: 'RIVN', name: 'Rivian', category: 'Stock' },
    { symbol: 'F', name: 'Ford', category: 'Stock' },
    { symbol: 'GM', name: 'General Motors', category: 'Stock' },
    { symbol: 'RACE', name: 'Ferrari', category: 'Stock' },

    // --- Stocks: Health / Biotech ---
    { symbol: 'LLY', name: 'Eli Lilly', category: 'Stock' },
    { symbol: 'NVO', name: 'Novo Nordisk', category: 'Stock' },
    { symbol: 'JNJ', name: 'Johnson & Johnson', category: 'Stock' },
    { symbol: 'UNH', name: 'UnitedHealth', category: 'Stock' },
    { symbol: 'PFE', name: 'Pfizer', category: 'Stock' },
    { symbol: 'ABBV', name: 'AbbVie', category: 'Stock' },
    { symbol: 'MRK', name: 'Merck', category: 'Stock' },
    { symbol: 'ISRG', name: 'Intuitive Surgical', category: 'Stock' },
    { symbol: 'AMGN', name: 'Amgen', category: 'Stock' },
    { symbol: 'GILD', name: 'Gilead Sciences', category: 'Stock' },
    { symbol: 'TMO', name: 'Thermo Fisher', category: 'Stock' },

    // --- Stocks: Energy ---
    { symbol: 'XOM', name: 'Exxon Mobil', category: 'Stock' },
    { symbol: 'CVX', name: 'Chevron', category: 'Stock' },
    { symbol: 'COP', name: 'ConocoPhillips', category: 'Stock' },
    { symbol: 'NEE', name: 'NextEra Energy', category: 'Stock' },
    { symbol: 'FSLR', name: 'First Solar', category: 'Stock' },

    // --- Stocks: Defense / Industrial ---
    { symbol: 'CAT', name: 'Caterpillar', category: 'Stock' },
    { symbol: 'GE', name: 'General Electric', category: 'Stock' },
    { symbol: 'BA', name: 'Boeing', category: 'Stock' },
    { symbol: 'LMT', name: 'Lockheed Martin', category: 'Stock' },
    { symbol: 'RTX', name: 'RTX Corp', category: 'Stock' },
    { symbol: 'NOC', name: 'Northrop Grumman', category: 'Stock' },
    { symbol: 'GD', name: 'General Dynamics', category: 'Stock' },

    // --- Forex ---
    { symbol: 'EURUSD=X', name: 'EUR/USD', category: 'Forex' },
    { symbol: 'GBPUSD=X', name: 'GBP/USD', category: 'Forex' },
    { symbol: 'USDJPY=X', name: 'USD/JPY', category: 'Forex' },
    { symbol: 'USDCHF=X', name: 'USD/CHF', category: 'Forex' },
    { symbol: 'AUDUSD=X', name: 'AUD/USD', category: 'Forex' },
    { symbol: 'USDCAD=X', name: 'USD/CAD', category: 'Forex' },
    { symbol: 'EURGBP=X', name: 'EUR/GBP', category: 'Forex' },
    { symbol: 'NZDUSD=X', name: 'NZD/USD', category: 'Forex' },

    // --- Stocks: Germany (DAX) & Europe ---
    { symbol: 'SAP.DE', name: 'SAP', category: 'Stock' },
    { symbol: 'SIE.DE', name: 'Siemens', category: 'Stock' },
    { symbol: 'ALV.DE', name: 'Allianz', category: 'Stock' },
    { symbol: 'DTE.DE', name: 'Deutsche Telekom', category: 'Stock' },
    { symbol: 'AIR.DE', name: 'Airbus', category: 'Stock' },
    { symbol: 'BMW.DE', name: 'BMW', category: 'Stock' },
    { symbol: 'MBG.DE', name: 'Mercedes-Benz', category: 'Stock' },
    { symbol: 'VOW3.DE', name: 'Volkswagen', category: 'Stock' },
    { symbol: 'BAS.DE', name: 'BASF', category: 'Stock' },
    { symbol: 'IFX.DE', name: 'Infineon', category: 'Stock' },
    { symbol: 'ADS.DE', name: 'Adidas', category: 'Stock' },
    { symbol: 'DHL.DE', name: 'DHL Group', category: 'Stock' },
    { symbol: 'MUV2.DE', name: 'Munich Re', category: 'Stock' },
    { symbol: 'RHM.DE', name: 'Rheinmetall', category: 'Stock' },
    { symbol: 'DBK.DE', name: 'Deutsche Bank', category: 'Stock' },
    { symbol: 'ENR.DE', name: 'Siemens Energy', category: 'Stock' },
    { symbol: 'MC.PA', name: 'LVMH', category: 'Stock' },
    { symbol: 'OR.PA', name: 'L\'Oréal', category: 'Stock' },
    { symbol: 'RMS.PA', name: 'Hermès', category: 'Stock' },
    { symbol: 'TTE', name: 'TotalEnergies', category: 'Stock' },
    { symbol: 'SAN.PA', name: 'Sanofi', category: 'Stock' },
    { symbol: 'SHEL.L', name: 'Shell', category: 'Stock' },
    { symbol: 'AZN.L', name: 'AstraZeneca', category: 'Stock' },
];
